# OWASP TEA conformance suite.
#
# Every recipe reads config.yaml if it exists and falls back to
# config.example.yaml, so a fresh clone runs without editing anything.

config := if path_exists("config.yaml") == "true" { "config.yaml" } else { "config.example.yaml" }

# INTERNAL USE ONLY — see the `publish-hugo` recipe at the bottom of this file.
# Everything above it is for anybody running the suite; this one path publishes
# Vulnetix's own results into a Vulnetix repository that is not part of this
# project, and is useless to anyone else.
hugo_docs := env("VULNETIX_CLI_TEA_DOCS", "../cli/website/content/docs/tea")

_default:
    @just --list

# Compile the binary to ./bin/tea-conformance.
build:
    go build -o bin/tea-conformance ./cmd/tea-conformance

# Unit tests, including the validator's own negative controls.
test:
    go test ./...

fmt:
    gofmt -w .

vet:
    go vet ./...

lint: fmt vet

# Show what a run would do, without making a single request.
plan:
    go run ./cmd/tea-conformance --config {{config}} --plan

# Full run. Pass a provider name to narrow: `just run vulnetix`.
run provider="":
    go run ./cmd/tea-conformance --config {{config}} {{ if provider != "" { "--provider " + provider } else { "" } }}

# Run one area against one provider: `just area consumer vulnetix`.
area name provider="":
    go run ./cmd/tea-conformance --config {{config}} --area {{name}} {{ if provider != "" { "--provider " + provider } else { "" } }}

# Check every endpoint answers; store nothing, judge nothing, write nothing.
dryrun provider="":
    go run ./cmd/tea-conformance --config {{config}} --dryrun {{ if provider != "" { "--provider " + provider } else { "" } }}

# Regenerate reports from a previous run's directory with no network at all.
reproduce dir:
    go run ./cmd/tea-conformance --config {{config}} --reproduce-from-dir {{dir}}

# A normal run fetches the specifications itself, into its own run directory.
# This recipe is for inspecting what upstream currently says.

# Fetch the authoritative specifications into ./spec-preview and print digests.
fetch-specs:
    go run ./cmd/tea-conformance --config {{config}} --fetch-specs-to spec-preview

# ─── INTERNAL USE ONLY ──────────────────────────────────────────────────────
#
# Publishes a recorded run into the Vulnetix CLI documentation site, which is a
# separate private repository. It is here rather than there because the report
# format belongs to this suite: when a section is renamed the recipe that maps
# it onto Hugo pages should move in the same commit.
#
# Nobody outside Vulnetix has a reason to run this. It is not part of using the
# suite, nothing else depends on it, and deleting it would not affect a single
# conformance result. The generic way to publish a report is to read the
# Markdown in `reports/<provider>/reports/` and do whatever your own site needs.
#
# It writes into ../cli, which is another working copy on this machine. Override
# with VULNETIX_CLI_TEA_DOCS. Nothing is committed or pushed — the CLI repo has
# its own review and release process, and this only stages the files for it.
#
#   just publish-hugo                       # from reports/vulnetix
#   just publish-hugo reports/vulnetix      # explicit
#
# Reports are regenerated offline from the run's own recordings rather than
# copied, so what lands on the site is reproducible from the evidence beside it,
# and a stale hand-edit on either end shows up as a diff.

# INTERNAL: stage a recorded run into the Vulnetix CLI documentation site.
publish-hugo dir="reports/vulnetix":
    #!/usr/bin/env bash
    set -euo pipefail

    run_dir="{{dir}}"
    docs="{{hugo_docs}}"

    if [ ! -d "$run_dir/responses" ]; then
      echo "no recorded run at $run_dir — run 'just run vulnetix' first" >&2
      exit 1
    fi
    if [ ! -d "$docs" ]; then
      echo "the CLI documentation tree is not at $docs" >&2
      echo "set VULNETIX_CLI_TEA_DOCS to where it is checked out" >&2
      exit 1
    fi

    staging="$(mktemp -d)"
    trap 'rm -rf "$staging"' EXIT

    # Single-document Markdown: the Hugo page set has one conformance page, and
    # the split layout's inter-page links would resolve to nothing there.
    go run ./cmd/tea-conformance \
      --config {{config}} \
      --reproduce-from-dir "$run_dir" \
      --reports-to "$staging" \
      --markdown single \
      --quiet

    generated="$staging/$(basename "$run_dir")/reports"

    # Front matter is prepended rather than emitted by the suite: the weights
    # and descriptions belong to the site's information architecture, not to a
    # conformance report, and a report that carried them would be wrong
    # everywhere else.
    {
      printf -- '---\n'
      printf 'title: Conformance report\n'
      printf 'weight: 2\n'
      printf 'description: "Independent conformance and performance results for the Vulnetix TEA server, generated by the OWASP TEA conformance suite."\n'
      printf -- '---\n\n'
      # The suite writes an H1; Hugo renders the title from front matter, so
      # carrying both would print the heading twice.
      tail -n +2 "$generated/conformance.md"
    } > "$docs/conformance.md"

    if [ -f "$generated/catalogue.md" ]; then
      {
        printf -- '---\n'
        printf 'title: Open-source catalogue\n'
        printf 'weight: 3\n'
        printf 'description: "The open-source projects the Vulnetix TEA server publishes as TEA products, listed by paging the API itself."\n'
        printf -- '---\n\n'
        tail -n +2 "$generated/catalogue.md"
      } > "$docs/catalogue.md"
    fi

    # residual.md is deliberately NOT published. It names records left in a
    # catalogue for an operator to purge, which is an internal maintenance note
    # and not something a public documentation site should carry.

    echo "staged into $docs:"
    ls -1 "$docs"
    echo
    echo "review and commit in the CLI repository; nothing was committed here or there"
